import type { InsightExtractionInput, InsightExtractionProvider, TranscriptSegmentInput } from './types';

/**
 * Deterministic placeholder provider — it does not perform real
 * language understanding. It exists so the transcript -> insight
 * extraction -> editorial brief pipeline can be built, run, and tested
 * end to end (in both Arabic and English) before a real extraction
 * budget/API key is configured. Swap getInsightProvider() (./index.ts)
 * to a real provider once one is available.
 *
 * It treats Arabic as first-class rather than translated English: an
 * Arabic transcript gets Arabic scaffolding text (labels, hook
 * framing, qualification notes), not an English template around
 * untouched Arabic quotes.
 */
export const mockInsightProvider: InsightExtractionProvider = {
  name: 'mock',
  async extract({ segments, language, audience }: InsightExtractionInput) {
    if (segments.length === 0) {
      throw new Error('Cannot extract insights from an empty transcript.');
    }

    const isArabic = language === 'ar';
    const sorted = [...segments].sort((a, b) => a.startMs - b.startMs);
    const first = sorted[0];
    const longest = sorted.reduce((a, b) => (b.text.length > a.text.length ? b : a));

    const groups = splitIntoGroups(sorted, Math.min(3, sorted.length));
    const themes = groups.map((group, index) => ({
      id: `theme_${index + 1}`,
      label: isArabic ? `الموضوع ${index + 1}` : `Theme ${index + 1}`,
      summary: isArabic
        ? `[ملخص تجريبي] ${truncate(joinText(group), 160)}`
        : `[mock summary] ${truncate(joinText(group), 160)}`,
      evidence: group.map((segment) => segment.id),
    }));

    const keyPoints = sorted.slice(0, Math.min(3, sorted.length)).map((segment, index) => ({
      id: `key_point_${index + 1}`,
      text: segment.text,
      evidence: [segment.id],
    }));

    const quotes = [{ id: 'quote_1', text: longest.text, evidence: [longest.id] }];

    const hooks = [
      {
        id: 'hook_1',
        text: isArabic ? `هل تعلم؟ ${truncate(first.text, 120)}` : `Here's the thing: ${truncate(first.text, 120)}`,
        evidence: [first.id],
      },
    ];

    const candidateClips = [
      {
        id: 'clip_1',
        startMs: longest.startMs,
        endMs: longest.endMs,
        rationale: isArabic
          ? '[تجريبي] أطول مقطع في التفريغ النصي'
          : '[mock] longest segment in the transcript',
        evidence: [longest.id],
      },
    ];

    const claimSegment = sorted.find((segment) => /\d/.test(segment.text));
    const claims = claimSegment
      ? [
          {
            id: 'claim_1',
            text: claimSegment.text,
            qualification: isArabic
              ? 'رقم ذكره المتحدث؛ لم يتم التحقق منه بشكل مستقل.'
              : 'Figure as stated by the speaker; not independently verified.',
            evidence: [claimSegment.id],
          },
        ]
      : [];

    const ctaKeywords = isArabic ? ['اشترك', 'تابعنا'] : ['subscribe', 'follow us', 'sign up'];
    const ctaSegment = sorted.find((segment) =>
      ctaKeywords.some((keyword) => segment.text.toLowerCase().includes(keyword))
    );
    const callToAction = ctaSegment ? { text: ctaSegment.text, evidence: [ctaSegment.id] } : null;

    return {
      thesis: { text: truncate(first.text, 200), evidence: [first.id] },
      audience: audience || (isArabic ? 'غير محدد' : 'unspecified'),
      language,
      themes,
      keyPoints,
      quotes,
      hooks,
      candidateClips,
      claims,
      callToAction,
      confidenceNotes: isArabic
        ? 'تم إنشاء هذا الملخص بواسطة مزود تجريبي حتمي لأغراض التطوير فقط، وليس بواسطة نموذج لغوي حقيقي.'
        : 'Generated by a deterministic mock provider for development/testing only — not a real language model.',
    };
  },
};

function splitIntoGroups<T>(items: T[], groupCount: number): T[][] {
  if (groupCount <= 1) return [items];
  const groups: T[][] = Array.from({ length: groupCount }, () => []);
  items.forEach((item, index) => groups[index % groupCount].push(item));
  return groups.filter((group) => group.length > 0);
}

function joinText(segments: TranscriptSegmentInput[]): string {
  return segments.map((segment) => segment.text).join(' ');
}

function truncate(text: string, max: number): string {
  return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}

export type { InsightExtractionInput };
